creation_rules:
  - path_regex: .

    # gpg recipients:
    #   - diamondburned (repository owner)
    pgp: >-
      F6928B0358386997646EA876D78C4471CE776659

    # age recipients:
    #   - GitHub Actions
    age: >-
      age1t0ggh4vz5qa9vhznsyj4cj90w7agwr6qceyd90skhn5v9cvhh90qs7wkyf
