[book]
authors = ["diamondburned"]
language = "en"
multilingual = false
src = "src"
title = "User Guide for Diamond"
description = "This user guide is designed to help you understand the basics of operating, interacting with, and using Diamond."

[build]
build-dir = "dist"
create-missing = false
extra-watch-dirs = ["scripts", "preprocessors"]
use-default-preprocessors = false

[output.html]
preferred-dark-theme = "coal"
smart-punctuation = true
copy-fonts = false
additional-css = [
  "theme/mdbook-admonish.css",
  "theme/dist/styles.css",
  # "theme/dist/styles.css.map",
]
additional-js = [
  "scripts/dist/index.js",
  "scripts/dist/index.js.map",
  "scripts/dist/subsectionindex.json"
]
git-repository-url = "https://github.com/diamondburned/docs"
git-repository-icon = "fa-github"

[output.html.fold]
enable = false

[output.html.search]
enable = false

[output.markdown]

[output.terminal]
command = "./renderers/mdbook-terminal.ts"
base_url = "https://docs.0xd14.id/formats/terminal"

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.2" # do not edit: managed by `mdbook-admonish install`
after = ["encrypt"]

[preprocessor.index]

[preprocessor.toc-summary]
command = "preprocessors/toc-summary.ts"
after = ["index"]

[preprocessor.scss]
command = "preprocessors/scss.ts"

[preprocessor.scripts]
command = "preprocessors/scripts.ts"

[preprocessor.namevar]
command = "preprocessors/namevar.ts"
after = ["toc-summary", "scripts", "encrypt"]

[preprocessor.encrypt]
command = "preprocessors/encrypt.ts"
