[book]
authors = ["diamondburned"]
language = "en"
multilingual = false
src = "src"
title = "User Guide for Diamond"
description = "This user guide is designed to help you understand the basics of operating, interacting with, and using Diamond."

[build]
build-dir = "dist"
create-missing = false
extra-watch-dirs = ["scripts", "preprocessors"]
use-default-preprocessors = false

[output.html]
preferred-dark-theme = "coal"
smart-punctuation = true
copy-fonts = false
additional-css = ["theme/pagetoc.css", "theme/global.css"]
additional-js = [
  "theme/pagetoc.js",
  "scripts/dist/index.js",
  "scripts/dist/index.js.map",
  "scripts/dist/subsectionindex.json"
]
git-repository-url = "https://github.com/diamondburned/docs"
git-repository-icon = "fa-github"

[output.html.fold]
enable = false

[option.html.search]
enable = false

[preprocessor.index]

[preprocessor.toc-summary]
command = "preprocessors/toc-summary.ts"
after = ["index"]

[preprocessor.scripts]
command = "preprocessors/scripts.ts"

[preprocessor.pagetoc]
after = ["toc-summary"]

[preprocessor.namevar]
command = "preprocessors/namevar.ts"
after = ["pagetoc", "scripts"]
