name: Build

on:
  push:
    branches: ["*", "!main"]
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: nix build .#

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: result
